language: node_js
node_js:
- '7'
- '6'
- '5'
deploy:
  provider: heroku
  app: powerful-cove-69945
  api_key:
    secure: lXCQT2SiKsMor3xpDuGP3RCRE4cLgX7GP7kruKTlnDnPhVSAEftb63N0BUQiSH9n6Lh1Q4xgjgA7dAOvO0wiSMbNo3lN1czG1iuhCdT7waIhs52xeE/LxZZzZ12wOJjKsBOXBDKlWGHSASj/G4DloyS5/5wMt60jEGu2mfSTgPvwN8kaNOJpq/12Qabayn7XCSIUHwc+/R4SDaMrNI+jfWi76Jir8WPd1GZVHnE5/ep36dg7QF+M7Y6d4RW/FibqLWTudJPWfN6bT3EjTcdFsb9bL9pjawC1M4qlOx8E2QprfHnhxDHGRyWI/cXwORZoClq25oUjbZCgfRHaqBO+B2lVsTQ0gC+zuY+yBjG/zEu8G4KSO2A7dnJ1HFno4uJIpneVil9YvrU5TgcNlKXRRg10afyjg+ylbTcPQpK1hBYwP7U86WXJcCX/ihG5teCrGhGMjWCGQML//dKlrD5jaZee6f9a1Clww/DjWc5GlE3hWQBkn+WpWAVeIArbJ5ilx3MA/oq53D83hw587XA9jW41W7LVrjOHtk5CPMYPH6VJJ+kAkg//by7cxy0laKDYCQyYdo8uZ48Bl6s//bSw7wHAbd544nQ1PDUydWhwC2pqak1fC9U8/RmCGKIFHSOgPAlY0FEfimMbl0YBQ7itXHpv4Uk7oYab11yVT+lSmok=